[package]
name = "zilib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "zilib"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.20.0"
unicode_categories = "0.1.1"
